import React, { useState, useEffect } from 'react';
import { BrowserRouter, Routes, Route, useParams, Navigate } from 'react-router-dom';
import Layout from './components/Layout';
import AlbaranList from './components/AlbaranList';
import AlbaranForm from './components/AlbaranForm';
import AlbaranDetail from './components/AlbaranDetail';
import Dashboard from './components/Dashboard';
import { airtableService } from './services/airtable';
import type { Albaran } from './types';

// Edit Wrapper Component
const EditWrapper: React.FC<{ albaranes: Albaran[]; onUpdate: (data: Albaran) => Promise<void> }> = ({ albaranes, onUpdate }) => {
    const { id } = useParams<{ id: string }>();
    const albaran = albaranes.find(a => a.id === id);

    if (!albaran) return <Navigate to="/albaranes" />;

    return <AlbaranForm initialData={albaran} onSubmit={onUpdate} />;
};

function App() {
    const [albaranes, setAlbaranes] = useState<Albaran[]>([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);

    useEffect(() => {
        loadAlbaranes();
    }, []);

    const loadAlbaranes = async () => {
        try {
            setLoading(true);
            const data = await airtableService.getAll();
            setAlbaranes(data);
            setError(null);
        } catch (err) {
            setError('Error al cargar los albaranes. Por favor, verifica tu conexión y configuración.');
            console.error(err);
        } finally {
            setLoading(false);
        }
    };

    const handleCreate = async (newAlbaran: Albaran) => {
        try {
            // Remove ID as it's generated by Airtable
            const { id, ...albaranData } = newAlbaran;
            const created = await airtableService.create(albaranData);
            setAlbaranes(prev => [created, ...prev]);
        } catch (err) {
            alert('Error al crear el albarán');
            console.error(err);
        }
    };

    const handleUpdate = async (updatedAlbaran: Albaran) => {
        try {
            await airtableService.update(updatedAlbaran.id, updatedAlbaran);
            setAlbaranes(prev => prev.map(a => a.id === updatedAlbaran.id ? updatedAlbaran : a));
        } catch (err) {
            alert('Error al actualizar el albarán');
            console.error(err);
        }
    };

    const handleDelete = async (id: string) => {
        if (window.confirm('¿Estás seguro de que quieres eliminar este albarán?')) {
            try {
                await airtableService.delete(id);
                setAlbaranes(prev => prev.filter(a => a.id !== id));
            } catch (err) {
                alert('Error al eliminar el albarán');
                console.error(err);
            }
        }
    };

    if (loading) {
        return (
            <div className="flex h-screen items-center justify-center bg-gray-50">
                <div className="text-center">
                    <div className="w-16 h-16 border-4 border-blue-600 border-t-transparent rounded-full animate-spin mx-auto mb-4"></div>
                    <p className="text-gray-600">Cargando datos...</p>
                </div>
            </div>
        );
    }

    if (error) {
        return (
            <div className="flex h-screen items-center justify-center bg-gray-50">
                <div className="text-center max-w-md p-6 bg-white rounded-xl shadow-lg">
                    <div className="text-red-500 text-5xl mb-4">⚠️</div>
                    <h2 className="text-xl font-bold text-gray-900 mb-2">Error de Conexión</h2>
                    <p className="text-gray-600 mb-6">{error}</p>
                    <button
                        onClick={loadAlbaranes}
                        className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
                    >
                        Reintentar
                    </button>
                </div>
            </div>
        );
    }

    return (
        <BrowserRouter>
            <Layout>
                <Routes>
                    <Route path="/" element={<Dashboard albaranes={albaranes} />} />
                    <Route path="/albaranes" element={<AlbaranList albaranes={albaranes} onDelete={handleDelete} />} />
                    <Route path="/albaranes/new" element={<AlbaranForm onSubmit={handleCreate} />} />
                    <Route path="/albaranes/:id" element={<AlbaranDetail albaranes={albaranes} />} />
                    <Route path="/albaranes/:id/edit" element={
                        <EditWrapper albaranes={albaranes} onUpdate={handleUpdate} />
                    } />
                </Routes>
            </Layout>
        </BrowserRouter>
    );
}

export default App;
